version: '3'

services:
    app-db:
        environment: 
            MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
            MYSQL_DATABASE: 'app'
            MYSQL_USER: 'appuser'
            MYSQL_PASSWORD: 'apppassword'

    app-db-schema:
        build:
            context: ./db
        environment:
            DB_DATABASE: 'app' 
            DB_USER: 'appuser'
            DB_PASSWORD: 'apppassword'

    rest-services:
        build:
            context: ./services
        ports: 
            - 8080:80
        environment:
            DB_DATABASE: 'app' 
            DB_USER: 'appuser'
            DB_PASSWORD: 'apppassword'
            DB_HOST: 'app-db'

    web:
        build:
            context: ./web
        volumes: 
            - ./web/content:/usr/share/nginx/html

networks:
    backend:
        driver: bridge
    frontend:
        driver: bridge


