version: '3'

services:
    app-db:
        image: mysql
        environment: 
            MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
            MYSQL_DATABASE: 'app'
            MYSQL_USER: 'appuser'
            MYSQL_PASSWORD: 'apppassword'
        networks:
            - backend
        deploy:
            placement:
                constraints: [node.role == manager]

    app-db-schema:
        image: jluck/brownbag-db:1.0
        environment:
            DB_DATABASE: 'app' 
            DB_USER: 'appuser'
            DB_PASSWORD: 'apppassword'
        links:
            - app-db
        networks:
            - backend
        deploy:
            restart_policy:
                condition: 'none'

    rest-services:
        image: jluck/brownbag-guest-service:1.0
        environment:
            DB_DATABASE: 'app' 
            DB_USER: 'appuser'
            DB_PASSWORD: 'apppassword'
            DB_HOST: 'app-db'
        links:
            - app-db
        networks:
            - frontend
            - backend
        deploy:
            mode: replicated
            replicas: 2
            placement:
                constraints: [node.role == worker]


    web:
        image: jluck/brownbag-web:1.0
        ports: 
            - 80:80
        links:
            - rest-services
        networks:
            - frontend
        deploy:
            mode: replicated
            replicas: 3
            placement:
                constraints: [node.role == worker]
        
networks:
    backend:
        driver: overlay
    frontend:
        driver: overlay


