version: '2'

services:
    app-db:
        image: mysql
        networks:
            - backend

    app-db-schema:
        image: dockerbrownbag-schema
        links:
            - app-db
        depends_on:
            - app-db
        networks:
            - backend

networks:
    backend:
        driver: bridge


