version: '2'

services:
    app-db:
        image: mysql
        environment: 
            MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
            MYSQL_DATABASE: 'app'
            MYSQL_USER: 'appuser'
            MYSQL_PASSWORD: 'apppassword'
        networks:
            - backend

    app-db-schema:
        build:
            context: ./db
        image: dockerbrownbag-schema
        environment:
            DB_DATABASE: 'app' 
            DB_USER: 'appuser'
            DB_PASSWORD: 'apppassword'
        links:
            - app-db
        depends_on:
            - app-db
        networks:
            - backend

networks:
    backend:
        driver: bridge


