version: '2'

services:
    app-db:
        image: mysql
        networks:
            - backend

    app-db-schema:
        image: dockerbrownbag-schema
        links:
            - app-db
        depends_on:
            - app-db
        networks:
            - backend

    rest-services:
        image: rest-services
        ports: 
            - 8080:80
        links:
            - app-db
        depends_on:
            - app-db
        networks:
            - frontend
            - backend

    web:
        image: web
        ports: 
            - 80:80
        depends_on:
            - rest-services
        networks:
            - frontend
networks:
    backend:
        driver: bridge
    frontend:
        driver: bridge


