version: '3'

services:

    #https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-cli-run-prod-mode
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:5.5.0
        networks: 
            - logging
        #healthcheck:
            #test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:9200/_cat/health"]
            #timeout: 5s
        deploy:
            placement:
                constraints: [node.hostname == swarm-manager2]
            resources:
                reservations:
                    memory: 1536m

    filebeat:
        image: jluck/brownbag-filebeat
        volumes:
            - "/var/lib/docker/containers:/dockerlogs:ro"
        networks: 
            - logging
        depends_on:
            - logstash
        deploy:
            mode: global
    
    logstash:
        image: jluck/brownbag-logging
        networks: 
            - logging
        depends_on:
            - elasticsearch
        deploy:
            placement:
                constraints: [node.role == worker]

    kibana:
        image: docker.elastic.co/kibana/kibana:5.5.0
        ports: 
            - 5601:5601
        networks: 
            - logging
        depends_on: 
            - elasticsearch
        deploy:
            placement:
                constraints: [node.role == worker]

networks: 
    logging:
        driver: overlay


